name: Test If Popup Compile
on: [push, pull_request]

jobs:
  test-popup-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build popup
        run: make build-popup

  test-extension-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build extension
        run: make build-ext
